apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: prod
    istio-injection: enabled
  name: prod

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoapp
  namespace: prod
  labels:
    app: demoapp
    env: prod
    app.kubernetes.io/name: demoapp
    app.kubernetes.io/managed-by: dfh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demoapp
      env: prod
      app.kubernetes.io/name: demoapp
      app.kubernetes.io/managed-by: dfh
  template:
    metadata:
      labels:
        app: demoapp
        env: prod
        app.kubernetes.io/name: demoapp
        app.kubernetes.io/managed-by: dfh
    spec:
      containers:
        - name: main
          image: nginx:1.25
          env:
            - name: foo
              value: bar

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: login
  namespace: prod
  labels:
    app: login
    env: prod
    app.kubernetes.io/name: login
    app.kubernetes.io/managed-by: dfh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login
      env: prod
      app.kubernetes.io/name: login
      app.kubernetes.io/managed-by: dfh
  template:
    metadata:
      labels:
        app: login
        env: prod
        app.kubernetes.io/name: login
        app.kubernetes.io/managed-by: dfh
    spec:
      containers:
        - name: main
          image: alpine:latest
          command: ["ash", "-c", "while true; do wget demoapp -S --spider 2>&1 | grep Server; sleep 1; done"]
          env:
            - name: foo
              value: bar
      terminationGracePeriodSeconds: 3

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: broken
  namespace: prod
  labels:
    app: broken
    env: prod
    app.kubernetes.io/name: broken
    app.kubernetes.io/managed-by: dfh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broken
      env: prod
      app.kubernetes.io/name: broken
      app.kubernetes.io/managed-by: dfh
  template:
    metadata:
      labels:
        app: broken
        env: prod
        app.kubernetes.io/name: broken
        app.kubernetes.io/managed-by: dfh
    spec:
      containers:
        - name: main
          image: alpine:latest
          command: ["ash", "-c", "exit 1"]
          env:
            - name: foo
              value: bar

---

apiVersion: v1
kind: Service
metadata:
  name: demoapp
  namespace: prod
  labels:
    app: demoapp
    env: prod
    app.kubernetes.io/name: demoapp
    app.kubernetes.io/managed-by: dfh
spec:
  ports:
  - name: http2
    appProtocol: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: demoapp
  type: ClusterIP

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: demoapp
  namespace: prod
  labels:
    app: demoapp
    env: prod
    app.kubernetes.io/name: demoapp
    app.kubernetes.io/managed-by: dfh
spec:
  maxReplicas: 1
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: demoapp
  targetCPUUtilizationPercentage: 80

---

apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: demoapp
  namespace: prod
  labels:
    app: demoapp
    env: prod
    app.kubernetes.io/name: demoapp
    app.kubernetes.io/managed-by: dfh
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      name: demoapp
      env: prod
