apiVersion: apps/v1
kind: Deployment
metadata:
  name: ""
  namespace: ""
  labels: {}
spec:
  replicas: 1
  selector: {}
  template:
    metadata:
      labels: {}
    spec:
      containers:
        - name: ""
          image: ""
          env: []
